src/RansomGr/PubliciteBundle/Entity/PubPos.php
<?php

namespace RansomGr\PubliciteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * PubPos
 *
 * @ORM\Table(name="pub_pos")
 * @ORM\Entity(repositoryClass="RansomGr\PubliciteBundle\Repository\PubPosRepository")
 */
class PubPos
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\Column(name="pos", type="integer", unique=true)
     */
    private $position;

    /**
     * @var float
     *
     * @ORM\Column(name="price", type="float")
     */
    private $price;
    /**
     * @var float
     *
     * @ORM\Column(name="Click_price", type="float")
     */
    private $Clickprice;

    /**
     * @return float
     */
    public function getClickprice()
    {
        return $this->Clickprice;
    }

    /**
     * @param float $Clickprice
     */
    public function setClickprice($Clickprice)
    {
        $this->Clickprice = $Clickprice;
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set pos
     *
     * @param integer $pos
     *
     * @return PubPos
     */
    public function setPosition($pos)
    {
        $this->position = $pos;

        return $this;
    }
    /**
     * Set pos
     *
     * @param integer $pos
     *
     * @return PubPos
     */
    public function setPos($pos)
    {
        $this->position = $pos;

        return $this;
    }

    /**
     * Get position
     *
     * @return int
     */
    public function getPosition()
    {
        return $this->position;
    }

    public function getPos()
    {
        return $this->position;
    }

    /**
     * Set price
     *
     * @param float $price
     *
     * @return PubPos
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Get price
     *
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

}

src/RansomGr/PubliciteBundle/Entity/Publicite.php
<?php

namespace RansomGr\PubliciteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert ;
/**
 * Publicite
 *
 * @ORM\Table(name="publicite")
 * @ORM\Entity(repositoryClass="RansomGr\PubliciteBundle\Repository\PubliciteRepository")
 */
class Publicite
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;
    /**
     * @var string
     * @Assert\Image()
     * @ORM\Column(name="lien", type="string", length=255)
     */

    private $photo;
    /**
     * @var string
     *
     * @ORM\Column(name="photo", type="string", length=255)
     */
    private $lien;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_deb", type="date")
     */
    private $dateDebut;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_fin", type="date")
     */
    private $dateFin;
    /**
     *  @var \PubOwner
     * @ORM\ManyToOne(targetEntity="PubOwner")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="owner", referencedColumnName="id")
     * })
     */
    private $owner;
    /**
     *  @var \PubPos
     * @ORM\ManyToOne(targetEntity="PubPos")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="position", referencedColumnName="id")
     * })
     */
    private $position;

    /**
     * @var string
     *
     * @ORM\Column(name="approved", type="string")
     */
    private $approved;
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Publicite
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set photo
     *
     * @param string $photo
     *
     * @return Publicite
     */
    public function setPhoto($photo)
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return string
     */
    public function getLien()
    {
        return $this->lien;
    }

    /**
     * @param string $lien
     */
    public function setLien($lien)
    {
        $this->lien = $lien;
    }

    /**
     * Get photo
     *
     * @return string
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Publicite
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set dateDebut
     *
     * @param string $dateDebut
     *
     * @return Publicite
     */
    public function setDateDebut($dateDebut)
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    /**
     * Get dateDebut
     *
     * @return string
     */
    public function getDateDebut()
    {
        return $this->dateDebut;
    }

    /**
     * Set dateFin
     *
     * @param \DateTime $dateFin
     *
     * @return Publicite
     */
    public function setDateFin($dateFin)
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    /**
     * Get dateFin
     *
     * @return \DateTime
     */
    public function getDateFin()
    {
        return $this->dateFin;
    }

    /**
     * @return \PubOwner
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * @param \PubOwner $owner
     */
    public function setOwner($owner)
    {
        $this->owner = $owner;
    }

    /**
     * @return \PubPos
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * @param \PubPos $position
     */
    public function setPosition($position)
    {
        $this->position = $position;
    }

    /**
     * @return string
     */
    public function getApproved()
    {
        return $this->approved;
    }

    /**
     * @param string $approved
     */
    public function setApproved($approved)
    {
        $this->approved = $approved;
    }

}

src/RansomGr/PubliciteBundle/Form/PubliciteType.php
<?php

namespace RansomGr\PubliciteBundle\Form;

use RansomGr\PubliciteBundle\Entity\PubOwner;
use RansomGr\PubliciteBundle\Entity\PubPos;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PubliciteType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder->add('title')->
        add('photo',FileType::class,array('label' => 'Choisir une Image'))
            ->add('lien')
            ->add('description')
            ->add('dateDebut')
            ->add('dateFin')
            ->add('approved', ChoiceType::class, array(
                'choices' => array(
                    'oui' => 'y',
                    'rejeter' => 'r',
                    'pas encor' => 'ny',
                    'suspendu' => 's',
                    'active' => 'a'
                )))

            ->add('owner',EntityType::class, array('class' => PubOwner::class,'choice_label' => 'email'))
            ->add('position', EntityType::class, array('class' => PubPos::class,'choice_label' => 'position') );

    }
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'RansomGr\PubliciteBundle\Entity\Publicite'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'ransomgr_publicitebundle_publicite';
    }


}

src/RansomGr/PubliciteBundle/Controller/PubliciteController.php
<?php

namespace RansomGr\PubliciteBundle\Controller;

use DateTime;
use RansomGr\PubliciteBundle\Entity\Publicite;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;


/**
 * Publicite controller.
 *
 */
class PubliciteController extends Controller
{
    /**
     * Lists all publicite entities.
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $publicites = $em->getRepository('RansomGrPubliciteBundle:Publicite')->findAll();

        return $this->render('@RansomGrPublicite/publicite/index.html.twig', array(
            'publicites' => $publicites,
        ));
    }

    /**
     * Creates a new publicite entity.
     *
     */
    public function newAction(Request $request)
    {
        $publicite = new Publicite();
        $form = $this->createForm('RansomGr\PubliciteBundle\Form\PubliciteType', $publicite);
        $form->handleRequest($request);
        /**
         * @var UploadedFile $file
         */
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $file=$publicite->getPhoto();
            $photo=md5(uniqid()).'.'.$file->guessExtension();
            $file->move(
                $this->getParameter('image_directory'),$photo
            );
            $publicite->setPhoto($photo);
            $em->persist($publicite);
            $em->flush();

            return $this->redirectToRoute('Admin_Publicite_show', array('id' => $publicite->getId()));
        }

        return $this->render('@RansomGrPublicite/publicite/new.html.twig', array(
            'publicite' => $publicite,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a publicite entity.
     *
     */
    public function showAction(Publicite $publicite)
    {
        $deleteForm = $this->createDeleteForm($publicite);

        return $this->render('@RansomGrPublicite/publicite/show.html.twig', array(
            'publicite' => $publicite,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing publicite entity.
     *
     */
    public function editAction(Request $request, Publicite $publicite)
    {

        $deleteForm = $this->createDeleteForm($publicite);
        $publicite->setPhoto(
            new File($this->getParameter('image_directory').'/'.$publicite->getPhoto())

        );
        /**
         * @var UploadedFile $file
         */
        $file=$publicite->getPhoto();
        $editForm = $this->createForm('RansomGr\PubliciteBundle\Form\PubliciteType', $publicite);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {

            $file=$publicite->getPhoto();
            $photo=md5(uniqid()).'.'.$file->guessExtension();
            $file->move(
                $this->getParameter('image_directory'),$photo
            );

            $publicite->setPhoto($photo);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('Admin_Publicite_index', array('id' => $publicite->getId()));
        }

        return $this->render('@RansomGrPublicite/publicite/edit.html.twig', array(
            'publicite' => $publicite,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
            'photo'=> $file->getFilename()
        ));
    }

    /**
     * Deletes a publicite entity.
     *
     */
    public function deleteAction(Request $request, Publicite $publicite)
    {
        $form = $this->createDeleteForm($publicite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($publicite);
            $em->flush();
        }

        return $this->redirectToRoute('Admin_Publicite_index');
    }
    public function removeAction($id)
    {
        $em=$this->getDoctrine()->getManager();
        $publicite=$this->getDoctrine()->getManager()->getRepository("RansomGrPubliciteBundle:Publicite")->find($id);
        $em->remove($publicite);
        $em->flush();
        return $this->redirectToRoute('Admin_Publicite_index');
    }

    /**
     * Creates a form to delete a publicite entity.
     *
     * @param Publicite $publicite The publicite entity
     *
     * @return \Symfony\Component\Form\FormInterface
     */
    private function createDeleteForm(Publicite $publicite)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('Admin_Publicite_delete', array('id' => $publicite->getId())))
            ->setMethod('DELETE')
            ->getForm()
            ;
    }
    public function fetchAllActivePubsAction()
    {

        $em=$this->getDoctrine()->getManager();
        $pubs=$em->getRepository('RansomGrPubliciteBundle:Publicite')->findAllordered();
        $EligiblePubs=array();
        forEach($pubs as $pub)
        {
            if($pub->getDateDebut()<=(new DateTime())&&$pub->getDateFin()>=(new DateTime()))
                $EligiblePubs[]=$pub;
        }
   $content='';
        forEach($pubs as $pub)
        {
          $content.="<div  data-p='170.00' >
          <a href='".$pub->getLien()."' >
          <img data-u='image' src='/MySoulMate-Symphony/web/images/".$pub->getPhoto()."' ></a></div>";
        }
        return new JsonResponse(array('pubs'=>$content));
    }
}

src/RansomGr/PubliciteBundle/Resources/views/publicite/edit.html.twig
{% extends 'Layouts/Layout_BO.html.twig' %}

{% block content %}
    <style>
        .fileContainer {
            overflow: hidden;
            position: relative;
        }
        .fileContainer [type=file] {
            cursor: inherit;
            display: block;
            font-size: 999px;
            filter: alpha(opacity=0);
            min-height: 100%;
            min-width: 100%;
            opacity: 0;
            position: absolute;
            right: 0;
            text-align: right;
            top: 0;
        }
    </style>
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Publicite</h3>
                </div>
                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h3>Modifier Une Publicité</h3>
                            <h4><a href="{{ path('Admin_Publicite_index') }}">Retour a la liste</a></h4>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                       aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">Settings 1</a>
                                        </li>
                                        <li><a href="#">Settings 2</a>
                                        </li>
                                    </ul>
                                </li>
                                <li><a class="close-link"><i class="fa fa-close"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <br/>
                            {{ form_start(edit_form, { 'attr': {'class': 'form-horizontal form-label-left'}}) }}
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Titre</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ form_widget(edit_form.title, { 'attr': {'class': 'form-control col-md-7 col-xs-12'} }) }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Aperçu</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <img id="img" style="max-height:150px;max-width:150px;height:auto;width:auto;" src="{{ asset('images/') }}{{ photo }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Photo</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <label class="fileContainer form-control col-md-7 col-xs-12">  Ajouter Une Photo!{{ form_widget(edit_form.photo, { 'attr': {'class': 'form-control col-md-7 col-xs-12 '} }) }}</label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Description</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ form_widget(edit_form.description, { 'attr': {'class': 'form-control col-md-7 col-xs-12'} }) }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Date Debut</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ form_widget(edit_form.dateDebut, { 'attr': {'class': 'form-control col-md-7 col-xs-12  has-feedback-left date'} }) }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Date fin</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ form_widget(edit_form.dateFin, { 'attr': {'class': 'form-control col-md-7 col-xs-12'} }) }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Lien du site
                                    annonceur</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ form_widget(edit_form.lien, { 'attr': {'class': 'form-control col-md-7 col-xs-12'} }) }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                       for="title">Confirmation</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ form_widget(edit_form.approved, { 'attr': {'class': 'form-control col-md-7 col-xs-12'} }) }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Annonceur</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ form_widget(edit_form.owner, { 'attr': {'class': 'form-control col-md-7 col-xs-12','tabindex':'-1'} }) }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="title">Position</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{ form_widget(edit_form.position, { 'attr': {'class': 'select2_single form-control col-md-7 col-xs-12 ','tabindex':'-1'} }) }}
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button class="btn btn-success" type="submit">Modifier</button>
                                <button class="btn btn-primary" type="reset">Annuler</button>
                                <button class="btn btn-danger" type="button"
                                        onclick="if(confirm('Voulez vous vraiment \nSupprimer Cette Publicite?'))document.getElementsByName('form')[0].submit()">
                                    Supprimer
                                </button>
                            </div>
                            {{ form_end(edit_form) }}
                            {{ form_start(delete_form) }}
                            {{ form_end(delete_form) }}
                        </div>
                    </div>
                    <script src="{{ asset('FO_assets/jquery.js') }}"></script>
                    <script>
                        function readURL(input) {
                            if (input.files && input.files[0]) {
                                var reader = new FileReader();

                                reader.onload = function (e) {
                                    $('#img').attr('src', e.target.result);
                                }

                                reader.readAsDataURL(input.files[0]);
                            }
                        }

                        $("#ransomgr_publicitebundle_publicite_photo").change(function(){
                            readURL(this);
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/RansomGr/PubliciteBundle/Resources/views/publicite/show.html.twig
{% extends 'Layouts/Layout_BO.html.twig' %}

{% block content %}
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Publicite</h3>
                </div>
                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h3>Detail Publicite</h3>
                            <h4><a href="{{ path('Admin_Publicite_index') }}">Liste Publicites</a></h4>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                       aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">Settings 1</a>
                                        </li>
                                        <li><a href="#">Settings 2</a>
                                        </li>
                                    </ul>
                                </li>
                                <li><a class="close-link"><i class="fa fa-close"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>

                        <div class="x_content">
                            <br/>
                            <div class="col-md-12 col-sm-12 col-xs-12  profile_details">
                                <div class="well profile_view">
                                    <div class="col-sm-12">
                                        <h4 class="brief"><strong>Etat :</strong><i>{{ publicite.approved }}</i></h4>
                                        <div class="left col-xs-7">
                                            <h2><strong>Titre</strong> :{{ publicite.title }}</h2>
                                            <ul class="list-unstyled">
                                                {% set difference = date(publicite.dateFin).diff(date(publicite.dateDebut)) %}
                                                {% set leftDays = difference.days %}
                                                <li><strong>Prix total :</strong>{{ leftDays* publicite.position.price }} DT</li>
                                                <li><strong><a href="{{ publicite.lien }}">Lien</a></strong> #:{{ publicite.lien }}
                                                </li>
                                                <li><strong>Click Price :</strong>{{ publicite.position.clickprice }} DT</li>
                                                <p><strong>Description :</strong> {{ publicite.description }}</p>
                                            </ul>
                                        </div>
                                        <div class="right col-xs-5 text-center">
                                            <img src="{{ asset('images/') }}{{ publicite.photo }}" alt="" class=" img-responsive">
                                        </div>
                                    </div>

                                    <div class="col-xs-12 bottom text-center">
                                        <button class="btn btn-success" type="button"
                                                onclick="takeme_here('{{ path('Admin_Publicite_edit', { 'id': publicite.id }) }}')">
                                            Modifer
                                        </button>
                                        <button class="btn btn-danger" type="button"
                                                onclick="if(confirm('Voulez vous vraiment \nSupprimer Cette Position?'))takeme_here('{{ path('Admin_Publicite_delete', { 'id': publicite.id }) }}')">
                                            Supprimer
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <script>
                                function takeme_here(link) {
                                    window.location.href = link;
                                }
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}